### PR TITLE
Task Processor

### LINKED ISSUE #38: Task processor
Develop a means to manage long-running asynchronous tasks in one place

### PR DESCRIPTION
**Pull request by cryptoquick**
Closes #38

### CODE REVIEW

**Comment by kn0wmad** [comment]
We're going to find out SO many ways how NOT build the best possible p2p network... ;)

**Comment by cryptoquick** [comment]
> We're going to find out SO many ways how NOT build the best possible p2p network... ;)

HA! Ain't that the fucken truth :joy_cat:

**Review by kn0wmad — APPROVED** [review]

**Comment by cryptoquick** [comment]
@kn0wmad dude, it's kinda bad form to approve a draft PR that fails to build 😹

**Comment by kn0wmad** [comment]
That occurred to me, but I thought you just wanted me to see the code

**Comment by cryptoquick** [comment]
Well, at least it's somewhat better than instamerging your own PRs like I sometimes oftentimes rarely often do...

Besides, I'm Hunter Trujillo and my code looks so good~

**Pull request closed without merging**
