### PR TITLE
IPFS Embed

### LINKED ISSUE #33: IPFS Data
For IPFS HTTP API

- [x] Add image to IPFS
- [x] Show generated cid

### PR DESCRIPTION
**Pull request by cryptoquick**
- [x] new()
- [x] add()
- [x] get()

Closes #33

### CODE REVIEW

**Comment by cryptoquick** [comment]
@kn0wmad All three methods should be technically ready, but I need your help with one thing... I'm not sure how to style and submit the input field on the content page view to get this to work.

Please validate the following workflow:

1. Drag an image onto Fuzzr window when first opened to the dashboard, then switch to the publish page to see the image.
2. Also test the other way around, switch to publish page, and then drag image onto the Fuzzr window, and you should also see the image. (Either way should work because all update methods on each page should now be called when an update occurs)
3. The terminal should say something like: `Content successfully added to IPFS! Cid: bafyr4i...`
4. Copy this, switch to the Content tab, and paste that Cid into the field there. This is the piece I don't have figured out, but I think you can help me with. Not sure how to submit the input, and it needs some styles to be legible. Please make this look nice, and it should have good flexbox flow.

**Comment by cryptoquick** [comment]
I'm also pleased to see our application binary is only 25 megabytes in size. As I expected, it would be 10x smaller than similar apps. Observe:

Screenshot from 2020-12-11 07-12-20

**Review by kn0wmad — APPROVED** [review]
Wow, you did a ton of work here.  Looks awesome

**Comment by kn0wmad** [comment]
Tested good and new issue created ( #35 ) for text input

**Pull request merged**
